#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<string.h>
#include<signal.h>
#include<fcntl.h>
#include<dlfcn.h>
#include<wait.h>
#include<sys/wait.h>
#include<sys/time.h>
#include<dirent.h>
#include<semaphore.h>
#include<pthread.h>
#include<sys/ipc.h>
#include<sys/types.h>
#include<stdarg.h>
#include<sys/resource.h>
#include<sys/shm.h>
#include<pwd.h>
#include<grp.h>
#include<sys/msg.h>
#include<sys/stat.h>
#include<errno.h>
#include<sys/sem.h>
#include<ctype.h>
#include<math.h>
//#include<conio.h>
#include<limits.h>
